
-- ============================================
-- 03_alerts.sql
-- ============================================

USE SCHEMA ECOMMERCE_DB.MONITORING;

-- Pipeline health monitoring view
CREATE OR REPLACE VIEW PIPELINE_HEALTH AS
SELECT
    'Bronze Row Count'      AS METRIC,
    COUNT(*)::VARCHAR       AS VALUE
FROM ECOMMERCE_DB.BRONZE.RAW_ECOMMERCE_SALES

UNION ALL

SELECT
    'Silver Row Count',
    COUNT(*)::VARCHAR
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES

UNION ALL

SELECT
    'Row Count Match',
    CASE
        WHEN (SELECT COUNT(*) FROM ECOMMERCE_DB.BRONZE.RAW_ECOMMERCE_SALES) =
             (SELECT COUNT(*) FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES)
        THEN 'YES'
        ELSE 'NO - DATA LOSS DETECTED'
    END

UNION ALL

SELECT
    'Last Bronze Load',
    MAX(_LOADED_AT)::VARCHAR
FROM ECOMMERCE_DB.BRONZE.RAW_ECOMMERCE_SALES

UNION ALL

SELECT
    'Last Silver Transform',
    MAX(_TRANSFORMED_AT)::VARCHAR
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES;

-- Snowpipe monitoring
CREATE OR REPLACE VIEW SNOWPIPE_STATUS AS
SELECT
    PIPE_NAME,
    PIPE_SCHEMA,
    DEFINITION,
    IS_AUTOINGEST_ENABLED,
    NOTIFICATION_CHANNEL,
    CREATED_ON
FROM ECOMMERCE_DB.INFORMATION_SCHEMA.PIPES
WHERE PIPE_SCHEMA = 'STAGING';
