
-- ============================================
-- 01_kpi_views.sql
-- ============================================

USE SCHEMA ECOMMERCE_DB.GOLD;

-- Monthly Revenue Trend
CREATE OR REPLACE VIEW MONTHLY_REVENUE_TREND AS
SELECT
    ORDER_YEAR,
    ORDER_MONTH,
    COUNT(DISTINCT ORDER_ID)    AS TOTAL_ORDERS,
    ROUND(SUM(REVENUE_USD), 2)  AS MONTHLY_REVENUE,
    ROUND(AVG(REVENUE_USD), 2)  AS AVG_ORDER_VALUE,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1, 2
ORDER BY 1, 2;

-- Payment Method Analysis
CREATE OR REPLACE VIEW PAYMENT_METHOD_ANALYSIS AS
SELECT
    PAYMENT_METHOD,
    COUNT(DISTINCT ORDER_ID)    AS TOTAL_ORDERS,
    ROUND(SUM(REVENUE_USD), 2)  AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE_USD), 2)  AS AVG_ORDER_VALUE,
    ROUND(AVG(CUSTOMER_RATING), 2) AS AVG_RATING
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1
ORDER BY TOTAL_REVENUE DESC;

-- Delivery Performance
CREATE OR REPLACE VIEW DELIVERY_PERFORMANCE AS
SELECT
    DELIVERY_CATEGORY,
    COUNT(DISTINCT ORDER_ID)    AS TOTAL_ORDERS,
    ROUND(AVG(DELIVERY_DAYS), 1) AS AVG_DAYS,
    ROUND(AVG(CUSTOMER_RATING), 2) AS AVG_RATING,
    ROUND(
        SUM(CASE WHEN IS_RETURNED THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    ) AS RETURN_RATE_PCT
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1;

-- Top Customers by Revenue
CREATE OR REPLACE VIEW TOP_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_TIER,
    TOTAL_ORDERS,
    LIFETIME_REVENUE,
    AVG_ORDER_VALUE,
    FIRST_ORDER_DATE,
    LAST_ORDER_DATE,
    CUSTOMER_TENURE_DAYS,
    TOTAL_RETURNS
FROM ECOMMERCE_DB.GOLD.CUSTOMER_BEHAVIOR
ORDER BY LIFETIME_REVENUE DESC
LIMIT 100;
