
-- ============================================
-- 02_dashboard_queries.sql
-- ============================================

USE SCHEMA ECOMMERCE_DB.GOLD;

-- Year-over-Year Revenue Comparison
CREATE OR REPLACE VIEW YOY_REVENUE_COMPARISON AS
SELECT
    ORDER_YEAR,
    ROUND(SUM(REVENUE_USD), 2)          AS ANNUAL_REVENUE,
    COUNT(DISTINCT ORDER_ID)            AS ANNUAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID)         AS ANNUAL_CUSTOMERS,
    ROUND(AVG(REVENUE_USD), 2)          AS AVG_ORDER_VALUE,
    LAG(ROUND(SUM(REVENUE_USD), 2)) OVER (ORDER BY ORDER_YEAR) AS PREV_YEAR_REVENUE,
    ROUND(
        (SUM(REVENUE_USD) - LAG(SUM(REVENUE_USD)) OVER (ORDER BY ORDER_YEAR))
        / NULLIF(LAG(SUM(REVENUE_USD)) OVER (ORDER BY ORDER_YEAR), 0) * 100, 2
    ) AS REVENUE_GROWTH_PCT
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1
ORDER BY 1;

-- Region + Category Revenue Heatmap
CREATE OR REPLACE VIEW REGION_CATEGORY_HEATMAP AS
SELECT
    REGION,
    PRODUCT_CATEGORY,
    COUNT(DISTINCT ORDER_ID)    AS TOTAL_ORDERS,
    ROUND(SUM(REVENUE_USD), 2)  AS TOTAL_REVENUE,
    ROUND(AVG(CUSTOMER_RATING), 2) AS AVG_RATING
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1, 2
ORDER BY REGION, TOTAL_REVENUE DESC;

-- Discount Impact Analysis
CREATE OR REPLACE VIEW DISCOUNT_IMPACT AS
SELECT
    CASE
        WHEN DISCOUNT_PERCENT = 0 THEN 'No Discount'
        WHEN DISCOUNT_PERCENT <= 5 THEN '1-5%'
        WHEN DISCOUNT_PERCENT <= 10 THEN '6-10%'
        WHEN DISCOUNT_PERCENT <= 15 THEN '11-15%'
        ELSE '16-20%'
    END AS DISCOUNT_BAND,
    COUNT(DISTINCT ORDER_ID)        AS TOTAL_ORDERS,
    ROUND(SUM(REVENUE_USD), 2)      AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE_USD), 2)      AS AVG_ORDER_VALUE,
    ROUND(AVG(CUSTOMER_RATING), 2)  AS AVG_RATING,
    ROUND(
        SUM(CASE WHEN IS_RETURNED THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    ) AS RETURN_RATE_PCT
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1
ORDER BY 1;

-- Hourly/Daily Order Pattern (Day of Week)
CREATE OR REPLACE VIEW WEEKLY_ORDER_PATTERN AS
SELECT
    ORDER_DAY_OF_WEEK,
    COUNT(DISTINCT ORDER_ID)        AS TOTAL_ORDERS,
    ROUND(SUM(REVENUE_USD), 2)      AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE_USD), 2)      AS AVG_ORDER_VALUE
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1;
