
-- ============================================
-- 01_bronze_to_silver.sql
-- ============================================

USE SCHEMA ECOMMERCE_DB.SILVER;

-- Create the Silver (Cleaned) table
CREATE OR REPLACE TABLE CLEAN_ECOMMERCE_SALES (
    ORDER_ID            NUMBER          PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(100)    NOT NULL,
    PRODUCT_CATEGORY    VARCHAR(50),
    PRODUCT_PRICE_USD   FLOAT,
    QUANTITY            INT,
    ORDER_DATE          DATE,
    ORDER_YEAR          INT,
    ORDER_MONTH         INT,
    ORDER_QUARTER       INT,
    ORDER_DAY_OF_WEEK   VARCHAR(10),
    REGION              VARCHAR(50),
    PAYMENT_METHOD      VARCHAR(50),
    DELIVERY_DAYS       INT,
    IS_RETURNED         BOOLEAN,
    CUSTOMER_RATING     FLOAT,
    DISCOUNT_PERCENT    FLOAT,
    REVENUE_USD         FLOAT,
    GROSS_AMOUNT        FLOAT,
    DISCOUNT_AMOUNT     FLOAT,
    IS_HIGH_VALUE_ORDER BOOLEAN,
    DELIVERY_CATEGORY   VARCHAR(20),
    RATING_CATEGORY     VARCHAR(20),
    _LOADED_AT          TIMESTAMP_NTZ,
    _TRANSFORMED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR(500)
);

-- Transform and load from Bronze to Silver
INSERT INTO ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    INITCAP(TRIM(PRODUCT_CATEGORY))         AS PRODUCT_CATEGORY,
    PRODUCT_PRICE                           AS PRODUCT_PRICE_USD,
    QUANTITY,
    ORDER_DATE,
    YEAR(ORDER_DATE)                        AS ORDER_YEAR,
    MONTH(ORDER_DATE)                       AS ORDER_MONTH,
    QUARTER(ORDER_DATE)                     AS ORDER_QUARTER,
    DAYNAME(ORDER_DATE)                     AS ORDER_DAY_OF_WEEK,
    INITCAP(TRIM(REGION))                   AS REGION,
    INITCAP(TRIM(PAYMENT_METHOD))           AS PAYMENT_METHOD,
    DELIVERY_DAYS,
    CASE WHEN IS_RETURNED = 1 THEN TRUE ELSE FALSE END  AS IS_RETURNED,
    ROUND(CUSTOMER_RATING, 1)               AS CUSTOMER_RATING,
    DISCOUNT_PERCENT,
    ROUND(REVENUE, 2)                       AS REVENUE_USD,
    ROUND(PRODUCT_PRICE * QUANTITY, 2)      AS GROSS_AMOUNT,
    ROUND(PRODUCT_PRICE * QUANTITY * (DISCOUNT_PERCENT / 100), 2) AS DISCOUNT_AMOUNT,
    CASE WHEN REVENUE > 500 THEN TRUE ELSE FALSE END    AS IS_HIGH_VALUE_ORDER,
    CASE
        WHEN DELIVERY_DAYS <= 2 THEN 'Express'
        WHEN DELIVERY_DAYS <= 5 THEN 'Standard'
        ELSE 'Delayed'
    END                                     AS DELIVERY_CATEGORY,
    CASE
        WHEN CUSTOMER_RATING >= 4 THEN 'Positive'
        WHEN CUSTOMER_RATING >= 3 THEN 'Neutral'
        ELSE 'Negative'
    END                                     AS RATING_CATEGORY,
    _LOADED_AT,
    CURRENT_TIMESTAMP()                     AS _TRANSFORMED_AT,
    _SOURCE_FILE
FROM ECOMMERCE_DB.BRONZE.RAW_ECOMMERCE_SALES;

-- Verify
SELECT COUNT(*) AS TOTAL_ROWS FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES;
