
-- ============================================
-- 02_silver_to_gold.sql
-- ============================================

USE SCHEMA ECOMMERCE_DB.GOLD;

-- ============================
-- 1. Daily Sales Summary
-- ============================
CREATE OR REPLACE TABLE DAILY_SALES_SUMMARY AS
SELECT
    ORDER_DATE,
    ORDER_YEAR,
    ORDER_MONTH,
    ORDER_QUARTER,
    ORDER_DAY_OF_WEEK,
    COUNT(DISTINCT ORDER_ID)        AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID)     AS UNIQUE_CUSTOMERS,
    SUM(REVENUE_USD)                AS TOTAL_REVENUE,
    AVG(REVENUE_USD)                AS AVG_ORDER_VALUE,
    SUM(DISCOUNT_AMOUNT)            AS TOTAL_DISCOUNTS,
    SUM(CASE WHEN IS_RETURNED THEN 1 ELSE 0 END) AS RETURNED_ORDERS,
    ROUND(AVG(CUSTOMER_RATING), 2)  AS AVG_RATING,
    ROUND(AVG(DELIVERY_DAYS), 1)    AS AVG_DELIVERY_DAYS
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1, 2, 3, 4, 5;

-- ============================
-- 2. Product Category Performance
-- ============================
CREATE OR REPLACE TABLE PRODUCT_CATEGORY_PERFORMANCE AS
SELECT
    PRODUCT_CATEGORY,
    COUNT(DISTINCT ORDER_ID)        AS TOTAL_ORDERS,
    SUM(QUANTITY)                   AS TOTAL_UNITS_SOLD,
    SUM(REVENUE_USD)                AS TOTAL_REVENUE,
    AVG(REVENUE_USD)                AS AVG_ORDER_VALUE,
    ROUND(AVG(CUSTOMER_RATING), 2)  AS AVG_RATING,
    SUM(CASE WHEN IS_RETURNED THEN 1 ELSE 0 END) AS RETURN_COUNT,
    ROUND(
        SUM(CASE WHEN IS_RETURNED THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    )                               AS RETURN_RATE_PCT,
    ROUND(AVG(DELIVERY_DAYS), 1)    AS AVG_DELIVERY_DAYS
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1
ORDER BY TOTAL_REVENUE DESC;

-- ============================
-- 3. Regional Sales Dashboard
-- ============================
CREATE OR REPLACE TABLE REGIONAL_SALES_DASHBOARD AS
SELECT
    REGION,
    ORDER_YEAR,
    ORDER_QUARTER,
    PAYMENT_METHOD,
    COUNT(DISTINCT ORDER_ID)        AS TOTAL_ORDERS,
    SUM(REVENUE_USD)                AS TOTAL_REVENUE,
    AVG(DISCOUNT_PERCENT)           AS AVG_DISCOUNT_PCT,
    ROUND(AVG(DELIVERY_DAYS), 1)    AS AVG_DELIVERY_DAYS,
    SUM(CASE WHEN IS_RETURNED THEN 1 ELSE 0 END) AS RETURNED_ORDERS
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1, 2, 3, 4;

-- ============================
-- 4. Customer Behavior Analysis
-- ============================
CREATE OR REPLACE TABLE CUSTOMER_BEHAVIOR AS
SELECT
    CUSTOMER_ID,
    COUNT(DISTINCT ORDER_ID)                    AS TOTAL_ORDERS,
    SUM(REVENUE_USD)                            AS LIFETIME_REVENUE,
    AVG(REVENUE_USD)                            AS AVG_ORDER_VALUE,
    MIN(ORDER_DATE)                             AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE)                             AS LAST_ORDER_DATE,
    DATEDIFF('day', MIN(ORDER_DATE), MAX(ORDER_DATE)) AS CUSTOMER_TENURE_DAYS,
    ROUND(AVG(CUSTOMER_RATING), 2)              AS AVG_RATING,
    SUM(CASE WHEN IS_RETURNED THEN 1 ELSE 0 END) AS TOTAL_RETURNS,
    CASE
        WHEN SUM(REVENUE_USD) >= 5000 THEN 'Platinum'
        WHEN SUM(REVENUE_USD) >= 2000 THEN 'Gold'
        WHEN SUM(REVENUE_USD) >= 500  THEN 'Silver'
        ELSE 'Bronze'
    END                                         AS CUSTOMER_TIER
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
GROUP BY 1;

-- ============================
-- 5. Executive KPI Summary
-- ============================
CREATE OR REPLACE VIEW EXECUTIVE_KPI_SUMMARY AS
SELECT
    COUNT(DISTINCT ORDER_ID)                AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID)             AS TOTAL_CUSTOMERS,
    ROUND(SUM(REVENUE_USD), 2)              AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE_USD), 2)              AS AVG_ORDER_VALUE,
    ROUND(AVG(CUSTOMER_RATING), 2)          AS AVG_CUSTOMER_RATING,
    ROUND(AVG(DELIVERY_DAYS), 1)            AS AVG_DELIVERY_DAYS,
    ROUND(
        SUM(CASE WHEN IS_RETURNED THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    )                                       AS OVERALL_RETURN_RATE_PCT,
    ROUND(SUM(DISCOUNT_AMOUNT), 2)          AS TOTAL_DISCOUNTS_GIVEN
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES;
