
-- ============================================
-- 03_data_quality_checks.sql
-- ============================================

USE SCHEMA ECOMMERCE_DB.MONITORING;

CREATE OR REPLACE VIEW DATA_QUALITY_REPORT AS
SELECT
    'Total Records'         AS CHECK_NAME,
    COUNT(*)::VARCHAR       AS CHECK_VALUE,
    'INFO'                  AS SEVERITY
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES

UNION ALL

SELECT
    'Null Customer IDs',
    COUNT(*)::VARCHAR,
    CASE WHEN COUNT(*) > 0 THEN 'WARNING' ELSE 'PASS' END
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
WHERE CUSTOMER_ID IS NULL

UNION ALL

SELECT
    'Negative Revenue',
    COUNT(*)::VARCHAR,
    CASE WHEN COUNT(*) > 0 THEN 'CRITICAL' ELSE 'PASS' END
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
WHERE REVENUE_USD < 0

UNION ALL

SELECT
    'Future Order Dates',
    COUNT(*)::VARCHAR,
    CASE WHEN COUNT(*) > 0 THEN 'WARNING' ELSE 'PASS' END
FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
WHERE ORDER_DATE > CURRENT_DATE()

UNION ALL

SELECT
    'Duplicate Order IDs',
    COUNT(*)::VARCHAR,
    CASE WHEN COUNT(*) > 0 THEN 'CRITICAL' ELSE 'PASS' END
FROM (
    SELECT ORDER_ID FROM ECOMMERCE_DB.SILVER.CLEAN_ECOMMERCE_SALES
    GROUP BY ORDER_ID HAVING COUNT(*) > 1
);
