USE ROLE ACCOUNTADMIN;

-- Create project-specific roles
CREATE OR REPLACE ROLE ECOMMERCE_DEVELOPER;
CREATE OR REPLACE ROLE ECOMMERCE_ANALYST;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE ECOMMERCE_DEVELOPER;
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE ECOMMERCE_ANALYST;

-- Developer gets full access
GRANT ALL PRIVILEGES ON DATABASE ECOMMERCE_DB TO ROLE ECOMMERCE_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE ECOMMERCE_DEVELOPER;

-- Analyst gets read access to GOLD only
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE ECOMMERCE_ANALYST;
GRANT USAGE ON SCHEMA ECOMMERCE_DB.GOLD TO ROLE ECOMMERCE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_DB.GOLD TO ROLE ECOMMERCE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.GOLD TO ROLE ECOMMERCE_ANALYST;

-- Assign roles to your user (replace with your Snowflake username)
GRANT ROLE ECOMMERCE_DEVELOPER TO USER HARSHA;
GRANT ROLE ECOMMERCE_ANALYST TO USER HARSHA;
