CREATE OR REPLACE WAREHOUSE ECOMMERCE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for E-Commerce Data Pipeline';

USE WAREHOUSE ECOMMERCE_WH;
