USE SCHEMA ECOMMERCE_DB.STAGING;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    COMMENT = 'Standard CSV file format for e-commerce data';

-- Verify the file format was created
SHOW FILE FORMATS IN SCHEMA ECOMMERCE_DB.STAGING;
