
-- ============================================
-- 05_copy_into.sql
-- ============================================

USE SCHEMA ECOMMERCE_DB.BRONZE;

-- Create the Bronze (Raw) table
CREATE OR REPLACE TABLE RAW_ECOMMERCE_SALES (
    ORDER_ID            NUMBER,
    CUSTOMER_ID         VARCHAR(100),
    PRODUCT_CATEGORY    VARCHAR(50),
    PRODUCT_PRICE       FLOAT,
    QUANTITY            INT,
    ORDER_DATE          DATE,
    REGION              VARCHAR(50),
    PAYMENT_METHOD      VARCHAR(50),
    DELIVERY_DAYS       INT,
    IS_RETURNED         INT,
    CUSTOMER_RATING     FLOAT,
    DISCOUNT_PERCENT    FLOAT,
    REVENUE             FLOAT,
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR(500)
);

-- Initial bulk load from S3 stage
COPY INTO ECOMMERCE_DB.BRONZE.RAW_ECOMMERCE_SALES (
    ORDER_ID, CUSTOMER_ID, PRODUCT_CATEGORY, PRODUCT_PRICE,
    QUANTITY, ORDER_DATE, REGION, PAYMENT_METHOD,
    DELIVERY_DAYS, IS_RETURNED, CUSTOMER_RATING, DISCOUNT_PERCENT,
    REVENUE, _SOURCE_FILE
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
        METADATA$FILENAME
    FROM @ECOMMERCE_DB.STAGING.S3_ECOMMERCE_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'ECOMMERCE_DB.STAGING.CSV_FORMAT')
ON_ERROR = 'CONTINUE';

-- Verify the load
SELECT COUNT(*) AS TOTAL_ROWS FROM ECOMMERCE_DB.BRONZE.RAW_ECOMMERCE_SALES;
-- Should return ~100,000 rows

-- Quick data check
SELECT * FROM ECOMMERCE_DB.BRONZE.RAW_ECOMMERCE_SALES LIMIT 10;
